import type { Metadata } from "next";
import { Archivo, Inter } from "next/font/google";
import "./globals.css";



const archivo = Archivo({
    subsets: ['latin'],
    weight: ['400', '500', '700'], // Choose weights you need
    variable: '--font-archivo',   // Optional: add a CSS variable
    display: 'swap',
});

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${archivo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
